### ISSUE TITLE
How to modify the Docker file to install and configure PostgreSQL instead of MongoDB?

### ISSUE THREAD

**Issue by yogeshvachhani** [openblocks-dev/openblocks#388]
I want to try out OpenBlocks.

I have setup Docker but when I checked the yml file I observed it installs MongoDB. But instead of MongoDB I want to use PostgreSQL and MySQL.

How to add these two RDBMS and build the docker image?

**Comment by as-shura** [comment]
Have a look at **ferretdb**. It is a layer on top of Postgres written in Go which is a dead replacement for MongoDB.

```
version: "3"

services:


  ferretdb:
    image: ghcr.io/ferretdb/ferretdb
    restart: on-failure
    ports:
      - 27017:27017
    expose:
      - 27017
    environment:
      - FERRETDB_POSTGRESQL_URL=postgres://postgres:5432/ferretdb
      - FERRETDB_HANDLER=pg
    networks:
      - databases


networks:
  databases:
    external:
      name: databases

```
