### ISSUE TITLE
Having issues with Java part on Odroid-C2 arm64

### ISSUE THREAD

**Issue by as-shura** [openblocks-dev/openblocks#394]
This is my stack on Portainer:

```
version: "3"
services:

  ##
  ## Start Openblocks backend services (api-service and node-service)
  ##
  openblocks-api-service:
    image: openblocksdev/openblocks-ce-api-service:latest
    # Enabled ports to be able to access backend from host
    ports:
      - "8080:8080"
    environment:
      PUID: "9001"
      PGID: "9001"
      REDIS_ENABLED: "true"
      MONGODB_ENABLED: "true"
      FRONTEND_ENABLED: "true"
      MONGODB_URI: "mongodb://openblocks:openblocks@ferretdb:27017/openblocks?authMechanism=PLAIN"
      REDIS_URL: "redis://redis:6379"
      JS_EXECUTOR_URI: "http://openblocks-node-service:6060"
      ENCRYPTION_PASSWORD: "openblocks.dev"
      ENCRYPTION_SALT: "openblocks.dev"
      CORS_ALLOWED_DOMAINS: "*"
    depends_on:
      - ferretdb
      - redis
    networks:
      - databases
      
  openblocks-node-service:
    image: openblocksdev/openblocks-ce-node-service:latest

    # Enabled ports to be able to access backend from host
    # ports:
    #   - "6060:6060"
    environment:
      PUID: "9001"
      PGID: "9001"
      OPENBLOCKS_API_SERVICE_URL: "http://openblocks-api-service:8080"
    restart: unless-stopped
    depends_on:
      - openblocks-api-service
    networks:
      - databases
      
  ##
  ## Start Openblocks web frontend
  ##
  openblocks-frontend:
    image: openblocksdev/openblocks-ce-frontend:latest
    ports:
      - "3000:3000"
    environment:
      PUID: "9001"
      PGID: "9001"
      OPENBLOCKS_API_SERVICE_URL: "http://openblocks-api-service:8080"
      OPENBLOCKS_NODE_SERVICE_URL: "http://openblocks-node-service:6060"
    restart: unless-stopped
    depends_on:
      - openblocks-node-service
      - openblocks-api-service
    networks:
      - databases

networks:
  databases:
    external:
      name: databases

```
